baseURL = 'https://thirdcake.github.io/learn-grav-ja/'
languageCode = 'ja-jp'
title = 'Grav ドキュメント（日本語訳）'
hasCJKLanguage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

